language: ruby
rvm:
  - 2.4.6
  - 2.5.6
  - 2.6.4
gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
cache:
  bundler: true
script:
  - bundle exec rake test

matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: gemfiles/6.0.gemfile

  include:
    # Bleeding edge Ruby
    - rvm: ruby-head
      gemfile: gemfiles/6.0.gemfile

    # Next version of Rails
    - rvm: 2.5.0
      gemfile: gemfiles/edge.gemfile

    # Running one job to execute DANGER bot and linting
    - rvm: 2.5.0
      gemfile: gemfiles/6.0.gemfile
      script:
        - gem install danger
        - danger
        - bundle exec rake rubocop

  allow_failures:
    - rvm: ruby-head
    - rvm: 2.5.0
      gemfile: gemfiles/edge.gemfile
